// List of popular locations for suggestions
export const popularLocations = [
  // Developed Countries
  "USA",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "Singapore",
  "Ireland",
  "Switzerland",
  "Sweden",
  "Netherlands",
  "Norway",
  "Finland",
  "Denmark",
  "Belgium",
  "Austria",
  "Spain",
  "Italy",
  "Portugal",
  "Israel",
  "UAE",
  "Qatar",
  "Kuwait",
  "Czech Republic",
  "Taiwan",
  
  // Developing and Emerging Countries
  "India",
  "China",
  "Brazil",
  "Russia",
  "South Africa",
  "Mexico",
  "Indonesia",
  "Turkey",
  "Saudi Arabia",
  "Argentina",
  "Thailand",
  "Malaysia",
  "Vietnam",
  "Philippines",
  "Nigeria",
  "Egypt",
  "Pakistan",
  "Bangladesh",
  "Poland",
  "Hungary",
  "Chile",
  "Colombia",
  "Peru",
  "Morocco",
  "Kenya",
  "Ghana",
  "Ethiopia",
  "Tanzania",
  "Ukraine",
  "Romania",
  "Kazakhstan",
  
  // Regions
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Africa",
  "Middle East",
  "Southeast Asia",
  "East Asia",
  "South Asia",
  "Central America",
  "Caribbean",
  "Oceania",
  "Nordic Countries",
  "Scandinavia",
  "Mediterranean",
  "Latin America",
  "European Union",
  "APAC",
  "EMEA",
  "LATAM",
  
  // Work arrangements
  "Remote",
  "Hybrid",
  "Global",
  
  // Cities and specific locations
  // North America - USA
  "New York, NY, USA",
  "San Francisco, CA, USA",
  "Los Angeles, CA, USA",
  "Chicago, IL, USA",
  "Seattle, WA, USA",
  "Austin, TX, USA",
  "Boston, MA, USA",
  "Denver, CO, USA",
  "Atlanta, GA, USA",
  "Portland, OR, USA",
  "Washington, DC, USA",
  "San Diego, CA, USA",
  "Miami, FL, USA",
  "Dallas, TX, USA",
  "Houston, TX, USA",
  "Phoenix, AZ, USA",
  "Philadelphia, PA, USA",
  "Las Vegas, NV, USA",
  "Detroit, MI, USA",
  "Minneapolis, MN, USA",
  "Nashville, TN, USA",
  "Charlotte, NC, USA",
  "Raleigh, NC, USA",
  "Indianapolis, IN, USA",
  "Columbus, OH, USA",
  "Cleveland, OH, USA",
  "Pittsburgh, PA, USA",
  "Kansas City, MO, USA",
  "St. Louis, MO, USA",
  "Salt Lake City, UT, USA",
  "Orlando, FL, USA",
  "Tampa, FL, USA",
  "New Orleans, LA, USA",
  "Honolulu, HI, USA",
  "Anchorage, AK, USA",
  "San Jose, CA, USA",
  "Sacramento, CA, USA",
  "Oakland, CA, USA",
  "Cincinnati, OH, USA",
  "Buffalo, NY, USA",
  "Baltimore, MD, USA",
  "San Antonio, TX, USA",
  "Milwaukee, WI, USA",
  "Albuquerque, NM, USA",
  "Tucson, AZ, USA",
  "Fresno, CA, USA",
  "Long Beach, CA, USA",
  "Omaha, NE, USA",
  "Oklahoma City, OK, USA",
  "Louisville, KY, USA",
  "Memphis, TN, USA",
  "Tulsa, OK, USA",
  "Fort Worth, TX, USA",
  "El Paso, TX, USA",
  "Arlington, TX, USA",
  "Boise, ID, USA",
  "Richmond, VA, USA",
  "Norfolk, VA, USA",
  "Virginia Beach, VA, USA",
  "Providence, RI, USA",
  "Hartford, CT, USA",
  "Boulder, CO, USA",
  "Fort Collins, CO, USA",
  "Colorado Springs, CO, USA",
  "Asheville, NC, USA",
  "Charleston, SC, USA",
  "Savannah, GA, USA",
  "Birmingham, AL, USA",
  "Mobile, AL, USA",
  "Jacksonville, FL, USA",
  "Tallahassee, FL, USA",
  "Baton Rouge, LA, USA",
  "Springfield, MO, USA",
  "Des Moines, IA, USA",
  "Cedar Rapids, IA, USA",
  "Madison, WI, USA",
  "Green Bay, WI, USA",
  "Jackson, MS, USA",
  "Little Rock, AR, USA",
  "Fayetteville, AR, USA",
  "Sioux Falls, SD, USA",
  "Rapid City, SD, USA",
  "Fargo, ND, USA",
  "Bismarck, ND, USA",
  "Billings, MT, USA",
  "Missoula, MT, USA",
  "Bozeman, MT, USA",
  "Cheyenne, WY, USA",
  "Laramie, WY, USA",
  "Santa Fe, NM, USA",
  "Las Cruces, NM, USA",
  "Flagstaff, AZ, USA",
  "Scottsdale, AZ, USA",
  "Mesa, AZ, USA",
  "Provo, UT, USA",
  "Ogden, UT, USA",
  "Reno, NV, USA",
  "Henderson, NV, USA",
  "Eugene, OR, USA",
  "Salem, OR, USA",
  "Olympia, WA, USA",
  "Spokane, WA, USA",
  "Tacoma, WA, USA",
  // Canada
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Edmonton, Canada",
  "Winnipeg, Canada",
  "Quebec City, Canada",
  "Hamilton, Canada",
  "Halifax, Canada",
  "Victoria, Canada",
  "London, Canada",
  "Kitchener, Canada",
  "Windsor, Canada",
  "Oshawa, Canada",
  "Saskatoon, Canada",
  "Regina, Canada",
  "St. John's, Canada",
  "Kelowna, Canada",
  "Abbotsford, Canada",
  "Kingston, Canada",
  "Guelph, Canada",
  "Barrie, Canada",
  "Moncton, Canada",
  "Thunder Bay, Canada",
  "Fredericton, Canada",
  "Sherbrooke, Canada",
  "Red Deer, Canada",
  "Sudbury, Canada",
  "Kamloops, Canada",
  "Chilliwack, Canada",
  "Niagara Falls, Canada",
  "Gatineau, Canada",
  "Lethbridge, Canada",
  "Saint John, Canada",
  "Nanaimo, Canada",
  "Burnaby, Canada",
  "Richmond, Canada",
  "Surrey, Canada",
  "Delta, Canada",
  "Coquitlam, Canada",
  "Langley, Canada",
  "Mississauga, Canada",
  "Brampton, Canada",
  "Markham, Canada",
  "Vaughan, Canada",
  "Waterloo, Canada",
  "Cambridge, Canada",
  "Burlington, Canada",
  "Oakville, Canada",
  "St. Catharines, Canada",
  "Laval, Canada",
  "Longueuil, Canada",
  // Europe
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Edinburgh, UK",
  "Glasgow, UK",
  "Liverpool, UK",
  "Bristol, UK",
  "Leeds, UK",
  "Sheffield, UK",
  "Newcastle, UK",
  "Belfast, UK",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Galway, Ireland",
  "Limerick, Ireland",
  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "Bordeaux, France",
  "Nice, France",
  "Toulouse, France",
  "Strasbourg, France",
  "Nantes, France",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Málaga, Spain",
  "Bilbao, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Turin, Italy",
  "Bologna, Italy",
  "Florence, Italy",
  "Venice, Italy",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Stuttgart, Germany",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Utrecht, Netherlands",
  "Brussels, Belgium",
  "Antwerp, Belgium",
  "Ghent, Belgium",
  "Vienna, Austria",
  "Graz, Austria",
  "Salzburg, Austria",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Basel, Switzerland",
  "Bern, Switzerland",
  "Lausanne, Switzerland",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Malmö, Sweden",
  "Copenhagen, Denmark",
  "Aarhus, Denmark",
  "Oslo, Norway",
  "Bergen, Norway",
  "Helsinki, Finland",
  "Tampere, Finland",
  "Reykjavik, Iceland",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Wrocław, Poland",
  "Poznań, Poland",
  "Prague, Czech Republic",
  "Brno, Czech Republic",
  "Budapest, Hungary",
  "Debrecen, Hungary",
  "Athens, Greece",
  "Thessaloniki, Greece",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Moscow, Russia",
  "St. Petersburg, Russia",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Sofia, Bulgaria",
  "Bucharest, Romania",
  "Zagreb, Croatia",
  "Ljubljana, Slovenia",
  // Asia - East Asia
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Yokohama, Japan",
  "Nagoya, Japan",
  "Sapporo, Japan",
  "Fukuoka, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Daegu, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Guangzhou, China",
  "Shenzhen, China",
  "Hong Kong",
  "Macau",
  "Taipei, Taiwan",
  "Kaohsiung, Taiwan",
  "Taichung, Taiwan",
  "Ulaanbaatar, Mongolia",
  // Asia - Southeast Asia
  "Singapore",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Phuket, Thailand",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Jakarta, Indonesia",
  "Bali, Indonesia",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Da Nang, Vietnam",
  "Yangon, Myanmar",
  "Phnom Penh, Cambodia",
  "Siem Reap, Cambodia",
  "Vientiane, Laos",
  "Bandar Seri Begawan, Brunei",
  // Asia - South Asia
  "Mumbai, India",
  "New Delhi, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Pune, India",
  "Ahmedabad, India",
  "Jaipur, India",
  "Kathmandu, Nepal",
  "Pokhara, Nepal",
  "Colombo, Sri Lanka",
  "Kandy, Sri Lanka",
  "Dhaka, Bangladesh",
  "Chittagong, Bangladesh",
  "Islamabad, Pakistan",
  "Lahore, Pakistan",
  "Karachi, Pakistan",
  "Thimphu, Bhutan",
  "Male, Maldives",
  // Asia - Central Asia
  "Almaty, Kazakhstan",
  "Astana, Kazakhstan",
  "Bishkek, Kyrgyzstan",
  "Tashkent, Uzbekistan",
  "Ashgabat, Turkmenistan",
  "Dushanbe, Tajikistan",
  // Asia - West Asia/Middle East
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Manama, Bahrain",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Tehran, Iran",
  "Baghdad, Iraq",
  "Damascus, Syria",
  "Erbil, Iraq",
  "Baku, Azerbaijan",
  "Yerevan, Armenia",
  "Tbilisi, Georgia",
  // Australia
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Gold Coast, Australia",
  "Canberra, Australia",
  "Hobart, Australia",
  "Darwin, Australia",
  "Newcastle, Australia",
  "Cairns, Australia",
  "Wollongong, Australia",
  "Geelong, Australia",
  "Townsville, Australia",
  "Launceston, Australia",
  "Alice Springs, Australia",
  // New Zealand
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Hamilton, New Zealand",
  "Tauranga, New Zealand",
  "Dunedin, New Zealand",
  "Queenstown, New Zealand",
  "Nelson, New Zealand",
  "Napier, New Zealand",
  "Rotorua, New Zealand",
  "Palmerston North, New Zealand",
  "Whangarei, New Zealand",
  "Invercargill, New Zealand",
  "Wanaka, New Zealand",
  "New Plymouth, New Zealand",
  "Gisborne, New Zealand",
  "Paraparaumu, New Zealand",
  "Motueka, New Zealand",
  "Suva, Fiji",
  "Port Moresby, Papua New Guinea",
  "Nouméa, New Caledonia",
  "Port Vila, Vanuatu",
  "Apia, Samoa",
  "Nuku'alofa, Tonga",
  "Honolulu, Hawaii, USA",
  
  // Africa
  "Cairo, Egypt",
  "Alexandria, Egypt",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Durban, South Africa",
  "Pretoria, South Africa",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Nairobi, Kenya",
  "Mombasa, Kenya",
  "Casablanca, Morocco",
  "Marrakech, Morocco",
  "Rabat, Morocco",
  "Accra, Ghana",
  "Kumasi, Ghana",
  "Addis Ababa, Ethiopia",
  "Tunis, Tunisia",
  "Algiers, Algeria",
  "Dakar, Senegal",
  "Dar es Salaam, Tanzania",
  "Kampala, Uganda",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
  "Kigali, Rwanda",
  "Windhoek, Namibia",
  "Gaborone, Botswana",
  "Maputo, Mozambique",
  "Libreville, Gabon",
  "Luanda, Angola",
  "Antananarivo, Madagascar",
  "Port Louis, Mauritius",
  "Djibouti, Djibouti",
  "Khartoum, Sudan",
  "Tripoli, Libya",
  "Nouakchott, Mauritania",
  "Bamako, Mali",
  "Niamey, Niger",
  "N'Djamena, Chad",
  "Ouagadougou, Burkina Faso",
  "Yaoundé, Cameroon",
  "Freetown, Sierra Leone",
  "Monrovia, Liberia",
  
  // South America
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Brasília, Brazil",
  "Salvador, Brazil",
  "Buenos Aires, Argentina",
  "Córdoba, Argentina",
  "Mendoza, Argentina",
  "Santiago, Chile",
  "Valparaíso, Chile",
  "Lima, Peru",
  "Cusco, Peru",
  "Bogotá, Colombia",
  "Medellín, Colombia",
  "Cartagena, Colombia",
  "Quito, Ecuador",
  "Guayaquil, Ecuador",
  "Caracas, Venezuela",
  "Montevideo, Uruguay",
  "Punta del Este, Uruguay",
  "Asunción, Paraguay",
  "La Paz, Bolivia",
  "Santa Cruz, Bolivia",
  "Georgetown, Guyana",
  "Paramaribo, Suriname",
  "Cayenne, French Guiana",
  "Remote"
];